### ISSUE TITLE
uge logfile locations

### ISSUE THREAD

**Issue by chrisgulvik** [gregorysprenger/wf-paired-end-illumina-assembly#1]
The UGE scheduler generates 4 logfiles for each job. Currently they're stored in the output path for the .uge-bash wrapper script, but would be be best to have them stored with all the other logfiles nextflow creates.

To-do:

- have UGE scheduler logfiles stored into nextflow's log/ dir

**Comment by gregorysprenger** [comment]
The bash wrapper script was updated to place the UGE STDOUT log files in the log directory with commit [23e31d7](https://github.com/gregorysprenger/wf-paired-end-illumina-assembly/commit/23e31d7c13cb407255ae8384f455783db2220558).
