### ISSUE TITLE
update MLST database

### ISSUE THREAD

**Issue by chrisgulvik** [gregorysprenger/wf-paired-end-illumina-assembly#4]
Currently we're using v2.17.6 [here](https://hub.docker.com/layers/snads/mlst/2.17.6/images/sha256-27f290753760c44204d6e04b6ead7935d03b48d5f0a5ccce068def9ce33babe6?context=explore)

We should update the `mlst` to use v2.23.0 [here](https://github.com/tseemann/mlst/tree/v2.23.0)

Aromatherapy **Bpseudomallei** samples will then show up as **ST-1941** instead of a novel arrangement

**Comment by gregorysprenger** [comment]
MLST has been updated to version 2.23.0 with commit [fc07ef5](https://github.com/gregorysprenger/wf-paired-end-illumina-assembly/commit/fc07ef599442ecf3e30c647b63e193ddcff155eb).
