### ISSUE TITLE
Feature request:  additional data columns in errors.tsv

### ISSUE THREAD

**Issue by chrisgulvik** [gregorysprenger/wf-paired-end-illumina-assembly#5]
The **errors.tsv** lists errors from each channel appended the the file, which is valuable to quickly identify parts that failed. It also allows technical inspection of the output dir/location on what happened (e.g., *.err, *.out, .exitcode and all the input and intermediate processed output files).

But when a re-run is performed on the same data, the previous errors show up too which is fine, but perhaps we could include additional info to clarify when they occurred. For example:
- 4th col date+timestamp (e.g., 2023-May-05 Fri 21:51:50 which is `date '+%Y-%b-%d %a %H:%M:%S'` in bash and `def trace_timestamp = new java.util.Date().format("yyyy-MMM-dd EEE HH:mm:ss")` in nf) and 
- 5th col nf run name (e.g., golden_brattain)

**Comment by gregorysprenger** [comment]
Commit [748438f](https://github.com/gregorysprenger/wf-paired-end-illumina-assembly/commit/748438fadd5dbcc847105e51ef548bf248d864b6) added timestamp and run name columns to `errors.tsv` file.
